wandb_version: 1

epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
T_max:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721760464
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.4
      5: 0.17.4
      8:
      - 3
      - 5
      13: windows-amd64
