wandb_version: 1

epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
width:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722972974
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.4
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
